<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">getFile</value>
  <value name="encodeutf8">true</value>
  <value name="body">SURhdGFNYXAgaW0gPSBuZXcgSURhdGFNYXAocGlwZWxpbmUpOw0KU3RyaW5nQnVpbGRlciBzYjsN
CkJ1ZmZlcmVkUmVhZGVyIGJ1Zj1udWxsOw0KdHJ5IHsNCglJbnB1dFN0cmVhbSBpcyA9IG5ldyBG
aWxlSW5wdXRTdHJlYW0oaW0uZ2V0QXNTdHJpbmcoImZpbGVQYXRoIikpOyANCglidWYgPSBuZXcg
QnVmZmVyZWRSZWFkZXIobmV3IElucHV0U3RyZWFtUmVhZGVyKGlzKSk7IA0KCVN0cmluZyBsaW5l
ID0gYnVmLnJlYWRMaW5lKCk7IHNiID0gbmV3IFN0cmluZ0J1aWxkZXIoKTsgDQoJd2hpbGUobGlu
ZSAhPSBudWxsKQ0KCXsNCgkJc2IuYXBwZW5kKGxpbmUpLmFwcGVuZCgiXG4iKTsgDQoJCWxpbmUg
PSBidWYucmVhZExpbmUoKTsgDQoJfQ0KCVN0cmluZyBmaWxlQXNTdHJpbmcgPSBzYi50b1N0cmlu
ZygpOw0KCWltLnB1dCgiZmlsZUNvbnRlbnQiLCBmaWxlQXNTdHJpbmcpOw0KfSBjYXRjaCAoRmls
ZU5vdEZvdW5kRXhjZXB0aW9uIGUpIHsNCgl0aHJvdyBuZXcgU2VydmljZUV4Y2VwdGlvbihlLmdl
dE1lc3NhZ2UoKSk7DQp9IGNhdGNoIChJT0V4Y2VwdGlvbiBlKSB7DQoJdGhyb3cgbmV3IFNlcnZp
Y2VFeGNlcHRpb24oZS5nZXRNZXNzYWdlKCkpOw0KfSANCmZpbmFsbHkNCnsNCgl0cnkgew0KCQlp
ZihidWYhPW51bGwpDQoJCXsNCgkJCWJ1Zi5jbG9zZSgpOw0KCQl9DQoJfSBjYXRjaCAoSU9FeGNl
cHRpb24gZSkgew0KCQl0aHJvdyBuZXcgU2VydmljZUV4Y2VwdGlvbihlLmdldE1lc3NhZ2UoKSk7
DQoJfQ0KfQ==</value>
</Values>
